import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import styles2 from '../styles/Layout.module.css';
import Header from './components/Header';
import NaviBar from './components/NaviBar';
import { AiFillHtml5 } from 'react-icons/ai';
import { DiCss3, DiReact, DiPostgresql, DiWordpress } from 'react-icons/di';
import { IoLogoJavascript } from 'react-icons/io';
import { SiJavascript } from 'react-icons/si';
import { FaNodeJs } from 'react-icons/fa';
import { GrGolang } from 'react-icons/gr';
import LottieControl from './components/lottie';
import LottieBook from './components/lottieBook';
import LottieServices from './components/lottieServices';
import Contact from './components/Contact';
import LottieContact from './components/LottieContact';
import Layout from './components/layout';


export default function Home() {
  const [show, setShow] = useState(false)

  const showProject = () => {
    setShow(!show)
    console.log(show)
  }

  return (
    <Layout>
      <div className={styles.container}>
        <Head>

          <title>Rubens Caio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        {/* <NaviBar />  */}



        <main className={styles.main}>
          <h1 className={styles.title3} id="about">Formação</h1>
          <div className={styles.lottie}> <LottieBook style=" z-index:-50;" /></div>
          <div>

            <div className={styles.grid}>
              <div className={styles.card}>
                <h2>Tecnologia em Sistemas de computação</h2>
                <div className={styles.experience}>
                  <div>
                    <p>Graduando em Tecnologia em Sistemas de computação, CEDERJ/UFF.</p>
                  </div>

                </div>
              </div>
              <div className={styles.card}>
                <h2>Mestrado em Matemática</h2>
                <div className={styles.experience}>
                  <div>
                    <p>Mestrado profissional pela UNIRIO, conluído no ano de 2020.</p>
                  </div>

                </div>
              </div>

              <div className={styles.card}>
                <h2>Graduação em Matemática</h2>
                <div className={styles.experience}>
                  <div>
                    <p>Licenciatura em Matemática pela FEUC, conluído em 2016.</p>
                  </div>
                </div>
              </div>

              <div className={styles.card}>
                <h2>Ensino médio Técnico em Informática</h2>
                <div className={styles.experience}>
                  <div>
                    <p>Ensino médio com foco na construção de programas na linguagem VB, conluído em 2011.</p>
                  </div>
                </div>
              </div>
            </div>
            <h1 className={styles.title3} id="about">Prêmios</h1>
            <div className={styles.lottie}><img src="/trofeu.png" alt="Vercel Logo" className={styles.imgxp} /></div>
            <div className={styles.grid}>
              <div className={styles.card}>
                <h2>Hackathon BTG - Open Finance - 2022</h2>
                
                <div className={styles.experience}>
                
                  <div>
                    <p>Evento do BTG em SP para inovações. Fomos a equipe campeã do prêmio Case Secreto, desafio revelado algumas horas antes do final do evento.</p>
                  </div>

                </div>
              </div>
            </div>

            <h1 className={styles.title3} id="experience">Experiência</h1>
          </div>
          <div className={styles.lottie}> <LottieControl style=" z-index:-50;" /></div>
          {/* <h1 className={styles.title} id="about">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

          <div className={styles.grid}>
            <div className={styles.card}>
              <h2>Desenvolvimento Frontend</h2>
              <div className={styles.experience}>
                <div>
                  <p><AiFillHtml5 /> Html</p>
                  <p>< DiCss3 /> Css</p>
                  <p><SiJavascript /> JavaScript</p>
                </div>
                <div>
                  <p><DiReact /> React.js</p>

                  <p><DiReact /> React Native</p>
                  <p><DiWordpress />   WordPress</p>
                </div>
              </div>
            </div>

            <div className={styles.card}>
              <h2>Desenvolvimento Backend BD{`'`}s</h2>
              <div className={styles.experience}>
                <div>
                  <p><FaNodeJs /> Node.js</p>
                  <p><SiJavascript /> Kotlin</p>
                  <p><Image src="/go.png" alt="Vercel Logo" width={30} height={30} /> </p>

                </div>
                <div>
                  <p><DiReact /> MySql</p>
                  <p> <DiPostgresql />Postgrees</p>

                </div>
              </div>
            </div>

            {/* <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}

          </div>
          <br></br>
          <button download="Rubens_Caio.pdf" onClick={() => showProject()} className={styles.buttonS}>{show? "Fechar projetos" : "Ver projetos"}</button>
          <div className={show ? styles.presentation2 : styles.presentation}>
            <h1 className={styles.titleShow} id="services">Projeto Lobinhos</h1>
            <p className={styles.descriptionProjects}>
              Esse projeto foi desenvolvido para a InJunior em janeiro de 2023.
              <br></br>
              Desenvolvido com html, css e js. Fique a vontade para testar o site abaixo.
            </p>
            <iframe src="/adote/index.html" className={styles.pdf} scrolling="no"></iframe>
            <h1 className={styles.titleShow} id="services">Projeto Comes & Bebes</h1>
            <p className={styles.descriptionProjects}>
              Esse projeto foi desenvolvido para a InJunior em janeiro de 2023, fui resposável pela parte de edição da conta.
              <br></br>
              Desenvolvido com WordPress e Woocommerce.
            </p>

            <img src="/wp.jpeg" alt="Vercel Logo" className={styles.imgProject} />
            <img src="/wp2.jpeg" alt="Vercel Logo" className={styles.imgProject} />
            <h1 className={styles.titleShow} id="services">Ciências Sob Tendas</h1>
            <p className={styles.descriptionProjects}>
              Sou responsável por adicionar novas funcionalidades no site do Ciências Sob Tendas.
              <br></br>
              Desenvolvido com WordPress. 
            </p>
            <img src="/cst.jpeg" alt="Vercel Logo" className={styles.imgProject} />
            
            
          </div>





          <h1 className={styles.title3} id="services">Serviços</h1>
          <div className={styles.lottie}> <LottieServices style=" z-index:-50;" /></div>
          <div className={styles.grid}>
            <div className={styles.card}>
              <h2>Serviços de consultoria</h2>
              <p>No último ano prestei serviços para pequenos negócios utilizando as tecnologias abaixo:</p>
              <div className={styles.experience}>
                <div>
                  <p><AiFillHtml5 /> Html</p>
                  <p>< DiCss3 /> Css</p>
                  <p><SiJavascript /> JavaScript</p>
                </div>
                <div>
                  <p><DiReact /> React.js</p>

                  <p><DiReact /> React Native</p>
                </div>
              </div>
            </div>

            <div className={styles.card}>
              <h2>UFF - Ciências Sob Tendas</h2>
              <p>Desenvolver aplicações em React Native, React.js, Arduino, atualizações do site em WordPress e desenho e impressões de material em 3d.</p>
              
            </div>




          </div>
          <h1 className={styles.title3} id="contact">Contato</h1>
          <div className={styles.lottie}> <LottieContact style=" z-index:-50;" /></div>
          <Contact />
          {/* <iframe src="https://www.ime.unicamp.br/~deleo/MS123/UERJ.pdf" className={styles.pdf}  ></iframe> */}
          {/* <iframe src="/adote/index.html" className={styles.pdf}  ></iframe> */}
        </main>



      </div>

    </Layout>
  )
}
