import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styles2 from '../styles/Layout.module.css'
import Header from './components/Header'
import NaviBar from './components/NaviBar'
import { AiFillHtml5 } from 'react-icons/ai'
import { DiCss3, DiReact, DiPostgresql } from 'react-icons/di'
import { IoLogoJavascript } from 'react-icons/io'
import { SiJavascript } from 'react-icons/si'
import { FaNodeJs } from 'react-icons/fa'
import { GrGolang } from 'react-icons/gr'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>

        <title>Rubens Caio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {/* <NaviBar />  */}



      <main className={styles.main}>
        <div>
          <p className={styles.text2}>Vamos falar </p>
          <h1 className={styles.title2}>Sobre minha experiência</h1>
        </div>
        {/* <h1 className={styles.title} id="about">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Desenvolvimento Frontend</h2>
            <div className={styles.experience}>
              <div>
                <p><AiFillHtml5 /> Html</p>
                <p>< DiCss3/> Css</p>
                <p><SiJavascript/> JavaScript</p>
              </div>
              <div>
                <p><DiReact/> React</p>
                <p> Next.js</p>
                <p><DiReact/> React Native</p>
              </div>
            </div>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Desenvolvimento Backend</h2>
            <div className={styles.experience}>
              <div>
                <p><FaNodeJs /> Node.js</p>
                <p><SiJavascript/> Kotlin</p>
                <p><Image src="/go.png" alt="Vercel Logo" width={30} height={30} /> </p>
                
              </div>
              <div>
                <p><DiReact/> MySql</p>
                <p> <DiPostgresql/>Postgrees</p>
               
              </div>
            </div>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <hr></hr>
    </div>
  )
}
