import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import styles2 from '../styles/Layout.module.css';
import Header from './components/Header';
import NaviBar from './components/NaviBar';
import { AiFillHtml5 } from 'react-icons/ai';
import { DiCss3, DiReact, DiPostgresql } from 'react-icons/di';
import { IoLogoJavascript } from 'react-icons/io';
import { SiJavascript } from 'react-icons/si';
import { FaNodeJs } from 'react-icons/fa';
import { GrGolang } from 'react-icons/gr';
import LottieControl from './components/lottie';
import LottieBook from './components/lottieBook';
import LottieServices from './components/lottieServices';
import Contact from './components/Contact';
import LottieContact from './components/LottieContact';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>

        <title>Rubens Caio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {/* <NaviBar />  */}

      
      
      <main className={styles.main}>
      
        <div>          
        <h1 className={styles.title3} id="about">Formação</h1>
        <LottieBook/>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Mestrado em Matemática</h2>
            <div className={styles.experience}>
              <div>
                <p>Mestrado profissional pela UNIRIO, conluído no ano de 2020.</p>
              </div>
              
            </div>
          </div>
        
          <div className={styles.card}>
            <h2>Graduação em Matemática</h2>
            <div className={styles.experience}>
              <div>
                <p>Licenciatura em Matemática pela FEUC, conluído em 2016.</p>
              </div>
            </div>
          </div>

          <div className={styles.card}>
            <h2>Ensino médio Técnico em Informática</h2>
            <div className={styles.experience}>
              <div>
                <p>Ensino médio com foco na construção de programas na linguagem VB, conluído em 2011.</p>
              </div>
            </div>
          </div>
        </div>
          <h1 className={styles.title3} id="experience">Experiência</h1>
        </div>
       <div className={styles.lottie}> <LottieControl /></div>
        {/* <h1 className={styles.title} id="about">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Desenvolvimento Frontend</h2>
            <div className={styles.experience}>
              <div>
                <p><AiFillHtml5 /> Html</p>
                <p>< DiCss3/> Css</p>
                <p><SiJavascript/> JavaScript</p>
              </div>
              <div>
                <p><DiReact/> React.js</p>
                
                <p><DiReact/> React Native</p>
              </div>
            </div>
          </div>
        
          <div className={styles.card}>
            <h2>Desenvolvimento Backend BD{`'`}s</h2>
            <div className={styles.experience}>
              <div>
                <p><FaNodeJs /> Node.js</p>
                <p><SiJavascript/> Kotlin</p>
                <p><Image src="/go.png" alt="Vercel Logo" width={30} height={30} /> </p>
                
              </div>
              <div>
                <p><DiReact/> MySql</p>
                <p> <DiPostgresql/>Postgrees</p>
               
              </div>
            </div>
          </div>
          
          {/* <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>

                  
        <h1 className={styles.title3}id="services">Serviços</h1>
        <LottieServices/>
        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Serviços de consultoria</h2>
            <p>No último ano prestei serviços para pequenos negocios utilizando as tecnologias abaixo:</p>
            <div className={styles.experience}>
              <div>
                <p><AiFillHtml5 /> Html</p>
                <p>< DiCss3/> Css</p>
                <p><SiJavascript/> JavaScript</p>
              </div>
              <div>
                <p><DiReact/> React.js</p>
                
                <p><DiReact/> React Native</p>
              </div>
            </div>
          </div>
        
         
                 
        
        </div>
        <h1 className={styles.title3} id="contact">Contato</h1>
      </main>
      <LottieContact/>
          <Contact />
      
    </div>
  )
}
